#!/bin/bash
# scan detection daemon by David Weinman <david@weinman.com>

# BT 5 / Kali
#IP_ADDR=$(DEV=$(./pdefdev); ifconfig | grep -A 3 $DEV | grep "inet")
#IP_ADDR=$(DEV=$(./pdefdev); ifconfig | grep -A 3 $DEV | grep "inet"); IP_ADDR="${IP_ADDR/inet addr:/}"; IP_ADDR=${IP_ADDR%%Bcast*}; IP_ADDR=${IP/ /} 
IP=$(DEV=$(./pdefdev); ifconfig $DEV | grep -o "192.*"); IP="${IP%%Bcast*}"; IP=${IP/ /}

# OSX 11
# NOTE: I found that my 'pdefdev.c program needs root privs to run, when I was working on it in os x.'
IP=$(DEV=$(sudo ./pdefdev); ifconfig $DEV | grep -o "192.*"); IP="${IP%%netmask*}"

PROCESS_ID=$(ps -C scan_detector -o pid= ); 

# if the cl args aren't equal to one, then print usage and exit
if [[ ! $# -eq 1 ]]; then

    echo "Usage: $0 [start | stop | status | clear | png]"
    exit

fi

# check for log files, if they don't exist, then make them.
if [[ -f "/var/logs/" ]]; then

    mkdir /var/logs/

fi

if [[ ! -f "/var/logs/scandetectd_graph.log" ]]; then

  touch "/var/logs/scandetectd_graph.log"
  touch "/var/logs/scandetectd.log"

elif [ "$PROCESS_ID" == "" ]; then

  if [ -f "/var/logs/scandetectd.log" ]; then

    rm "/var/logs/scandetectd_graph.log"
    touch "/var/logs/scandetectd_graph.log"

    rm "/var/logs/scandetectd.log"
    touch "/var/logs/scandetectd.log"

  fi

fi

if [ "$1" == "start" ]; then

  if [ ! "$PROCESS_ID" == "" ]; then
    echo "scandd already running!"
    exit
  fi

  echo "graph G {" >> /var/logs/scandetectd_graph.log
  ifconfig $DEV promisc
  ./scan_detector $IP 100

elif [ "$1" == "png" ]; then

  cp /var/logs/scandetectd_graph.log .neato_dat
  echo "overlap=false}" >> .neato_dat
  NOW=$(date +%F--%R%p); neato -Tpng -o $NOW .neato_dat

elif [ "$1" == "stop" ]; then

  if [ "$PROCESS_ID" == "" ]; then
    echo "error, nothing to kill?"
    exit
  fi

  kill $PROCESS_ID

elif [ "$1" == "status" ]; then

  cat /var/logs/scandetectd.log

elif [ "$1" == "clear" ]; then

  if [ ! "$PROCESS_ID" == "" ]; then
    echo "wait! there's a scan detection daemon running!"
    exit
  fi

  echo "" > /var/logs/scandetectd.log
  echo "" > /var/logs/scandetectd_graph.log

else

  echo "Usage: $0 [start | stop | status | clear | png]"
  exit

fi

PROCESS_ID=""
IP=""

