#!/bin/bash

# scan detection daemon by David Weinman <david@weinman.com>

# BT 5 / KALI
IP=$(DEV=$(./pdefdev); ifconfig $DEV | grep -o "192.*"); IP="${IP%%Bcast*}"; IP=${IP/ /}

# if the cl args aren't equal to one, then print usage and exit
if [[ ! $# -eq 1 ]]
  then
    echo "Usage: $0 [start | stop | status | png]"
    exit
fi

# check for log files, if they don't exist, then make them.
if [[ -f "/var/logs/" ]]
  then
    mkdir /var/logs/
fi
if [[ ! -f "/var/logs/scandetectd_graph.log" ]]
  then
    touch "/var/logs/scandetectd_graph.log"
fi
if [[ ! -f "/var/logs/scandetectd.log" ]]
  then
    touch "/var/logs/scandetectd.log"
fi

PROCESS_ID=$(ps -C scan_detector -o pid= ); 

if [ "$1" == "start" ]; then

  if [ ! "$PROCESS_ID" == "" ]; then
    echo "scandd already running!"
    exit
  fi

  echo "graph G {" >> /var/logs/scandetectd_graph.log
  ./scan_detector $IP 100

elif [ "$1" == "png" ]; then

  cp /var/logs/scandetectd_graph.log .neato_dat
  echo "overlap=false}" >> .neato_dat
  neato -Tpng -o neato4 .neato_dat

elif [ "$1" == "stop" ]; then

  if [ "$PROCESS_ID" == "" ]; then

    echo "error, nothing to kill?"
    exit

  fi
  kill $PROCESS_ID

elif [ "$1" == "status" ]; then

  cat /var/logs/scandetectd.log

fi

PROCESSID=""
IP=""



