#!/bin/bash

# ssd by David Weinman <david@weinman.com>

#DEV=$(./pdefdev)

# DARWIN CODE BELOW
# IP_ADDR=$(ifconfig | grep -A 3 $DEV | grep "inet ")

# BT 5
IP_ADDR=$(DEV=$(./pdefdev); ifconfig | grep -A 3 $DEV | grep "inet")

# DARWIN CODE BELOW
#IP_ADDR="${IP_ADDR/inet/}"

# BT 5
IP_ADDR="${IP_ADDR/inet addr:/}"

# DARWIN CODE BELOW
#IP_ADDR=${IP_ADDR%%netmask*}

# BT 5
IP_ADDR=${IP_ADDR%%Bcast*}

#
IP_ADDR=${IP_ADDR/ /}

echo "running with ip:$IP_ADDR"
./scan_detector $IP_ADDR 1000


